### ISSUE TITLE
Only 500 items will be synced - show warning or implement differently if needed

### ISSUE THREAD

**Issue by max-poprawe** [codeBeamer-Extensions-and-Addons/codebeamer-miro#16]
only first page of 500 is gotten and used. 500 items should be enough - more does not seem healthy. We should probably even ask the users when syncing 100 or more items, not to kill miro

**Comment by urecha** [comment]
Is this description outdated?

With the table-display on the picker page, at most 13 items are loaded at a time, with a max of 500 items lazy-loadable on pages 2-39.
The "import all" button does come with a warning when pressed, indicating how many items would be synched (and if 20+, displaying an additional warning: "This could take a while").

**Comment by urecha** [comment]
Additionally, no more than 100 items are ever synched at once, since that takes a fair amount of time already (~1 min). 
There's no limit in displaying items for import though.
