### ISSUE TITLE
Context item - open in new tab

### ISSUE THREAD

**Issue by max-poprawe** [codeBeamer-Extensions-and-Addons/codebeamer-miro#4]
We should probably use internal/external linking instead of the (currently commented out) attempt to use a context menu button. However, they can not be done programmatically at the moment

https://help.miro.com/hc/en-us/articles/360017572354-Internal-and-External-Linking
https://community.miro.com/developer-platform-forum-57/linking-to-inboard-object-using-sdk-672?postid=11570#post11570

**Comment by max-poprawe** [comment]
Does not seem to work. window.open does not do anything.
The links in the titles can also be clicked when the card is opened or small. If it is large it is difficult to know where to click
Its ok as it is.

function isSelectionOpenable(selectedWidgets) {
  // only single selection supported
  return !selectedWidgets.some(widget => !isWidgetRepresentingCodeBeamerItem(widget))
}

function isWidgetRepresentingCodeBeamerItem(widget) {
  return widget.metadata && widget.metadata[appId] && widget.metadata[appId].id
}


async function openInCodeBeamer(selectedWidgets) {
  selectedWidgets.forEach(widget => {
    console.log(`opening url '${getCodeBeamerItemURL(widget.metadata[appId].id)}'`)
    window.open(getCodeBeamerItemURL(widget.metadata[appId].id), '_blank')
  })
}

**Comment by max-poprawe** [comment]
reintroduced with db73e9b
This should be brought to work

**Comment by max-poprawe** [comment]
We should probably use internal/external linking

https://help.miro.com/hc/en-us/articles/360017572354-Internal-and-External-Linking
https://community.miro.com/developer-platform-forum-57/linking-to-inboard-object-using-sdk-672?postid=11570#post11570

**Comment by urecha** [comment]
Context menu is currently not available in SDK v2, but the addition of *App Cards* makes this obsolete anyway.  
App Cards, which we're using now, have their own *onOpen* event, which we can use to open a modal allowing to modify its values.
