### ISSUE TITLE
Support card Date <-> End date  sync

### ISSUE THREAD

**Issue by max-poprawe** [codeBeamer-Extensions-and-Addons/codebeamer-miro#9]

**Comment by urecha** [comment]
Start- & Enddate fields are displayed as tags if they're defined in codeBeamer by now. Is this what the task is about?

**Comment by urecha** [comment]
The card widget apparently has the `dueDate` property. So I imagine that's the one supposed to be synched with the cb end date.

**Comment by urecha** [comment]
Dropped in favour of a customField in which the item's dates can be displayed.
