### ISSUE TITLE
Bug: Sync stops at 50% without any message

### ISSUE THREAD

**Issue by kleinheny** [codeBeamer-Extensions-and-Addons/codebeamer-miro#98]
Hello team !
First, thanks for this great extension which I really like !
I am recently facing an issue when running Sync: the process starts fine but the modal dialog just disappears at 50% progress without any message (information, warning or error). I am not sure it actually updated all appcards (roughly 500 cards and progress disappears at around item 250).
I also tried to open dev tools console window to see if any console log shows, but nothing there either.
Any help is much appreciated !

**Comment by urecha** [comment]
Hello @kleinheny 

Thanks for your feedback and raising the issue.  
We have currently hardcoded the maximum amount of Items to be imported or updated at once to 250, it would seem.  
For updating, this should actually have been 500, but we're using the wrong constant for that.  

We can rectify this, but the amount remains arbitrary and we'd have to look into designing some better alternative to updating and synching items en masse in the future.

**Comment by kleinheny** [comment]
Hello @urecha ,

Thanks for the clarification.
Yes 500 would be already twice better ;-) !
For our last PI planning, we had almost 650 Retina cards on our board. Maybe we can find a way to "simplify" our miro board and get that number to max 500.
Appreciate your support !

**Comment by urecha** [comment]
Closed this Issue, but we've got a PBI on a more elaborate and scalable solution in our backlog.
